[compile_catalog]
directory = optimize_images_x/locale
domain = optimize_images_x
statistics = true

[extract_messages]
copyright_holder = Victor Domingos
msgid_bugs_address = victordomingos@no-title.victordomingos.com
charset = utf-8
output_file = optimize_images_x/locale/optimize_images_x.pot
width = 80

[wheel]
universal = 1

[options]
packages = find:

[options.packages.find]
include = optimize_images_x, optimize_images_x.*
